name: my_first_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_material_pickers: ^3.1.0
  path_provider: ^2.0.2
  http: ^0.13.3
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  just_audio: ^0.9.4
  flutter_tts: ^3.2.2
  flutter_local_notifications: ^8.0.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/icon/ic_clock_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  assets:
    - assets/icon/
    - assets/data/
    - assets/audio/
    - assets/gif/
  uses-material-design: true
